name: Build Fake Data
on:
  workflow_dispatch:
  schedule:
    - cron: "52 23 * * *"

jobs:
  build_fake_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      
      - name: Install dependencies
        run: poetry install --no-dev

      - name: Run python script
        run: python main.py

      - uses: actions/checkout@v2