name: Build Fake Data
on:
  workflow_dispatch:
  schedule:
    - cron: "52 22 * * *"

jobs:
  build_fake_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9.x"

      - name: Install Poetry
        uses: snok/install-poetry@v1
      
      - name: Install dependencies
        run: poetry install --without dev

      - name: Run python script
        run: poetry run python dbt_faker/main.py
        env:
          WAREHOUSE_URL: ${{ secrets.WAREHOUSE_URL }}
