name: Build Fake Data
on:
  workflow_dispatch:
  schedule:
    - cron: "52 22 * * *"

jobs:
  build_fake_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9.x"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
      
      - name: Install dependencies
        run: poetry install --only main

      - name: Run python script
        run: poetry run python dbt_faker/main.py
        env:
          WAREHOUSE_URL: ${{ secrets.WAREHOUSE_URL }}

      - uses: actions/checkout@v2
